# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7b3e13c9dc45e9924a0359124f5e9fc175716774d52bfdda061ef762f4d805c62fc163e3eac54f069e397b19019860795012dc10d039356f1157ed9d5f1cb02

test:
  secret_key_base: 63af104f0ceab7fd61c29072df92e857d05ea52bcafc1a6662ee903143359cc78e5e3c65e76ffad9d4e27eacfd718444f359e3165400ba009d47f69969c6100e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
